--
-- PostgreSQL database dump
--

-- Dumped from database version 13.0
-- Dumped by pg_dump version 13.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: administrador; Type: TABLE; Schema: public; Owner: rinq
--

CREATE TABLE public.administrador (
    siape character varying(9) NOT NULL,
    login character varying(255) NOT NULL
);


ALTER TABLE public.administrador OWNER TO rinq;

--
-- Name: aula; Type: TABLE; Schema: public; Owner: rinq
--

CREATE TABLE public.aula (
    id bigint NOT NULL,
    data date NOT NULL,
    observacao character varying(255),
    quantidade integer NOT NULL,
    id_disciplina bigint,
    siape_docente character varying(9)
);


ALTER TABLE public.aula OWNER TO rinq;

--
-- Name: aula_id_seq; Type: SEQUENCE; Schema: public; Owner: rinq
--

ALTER TABLE public.aula ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.aula_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: curso; Type: TABLE; Schema: public; Owner: rinq
--

CREATE TABLE public.curso (
    id bigint NOT NULL,
    nome character varying(100) NOT NULL,
    turno character varying(6) NOT NULL
);


ALTER TABLE public.curso OWNER TO rinq;

--
-- Name: curso_id_seq; Type: SEQUENCE; Schema: public; Owner: rinq
--

ALTER TABLE public.curso ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.curso_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: discente; Type: TABLE; Schema: public; Owner: rinq
--

CREATE TABLE public.discente (
    matricula character varying(11) NOT NULL,
    login character varying(255) NOT NULL,
    id_curso bigint
);


ALTER TABLE public.discente OWNER TO rinq;

--
-- Name: discente_disciplina; Type: TABLE; Schema: public; Owner: rinq
--

CREATE TABLE public.discente_disciplina (
    id_disciplina bigint NOT NULL,
    cpf_discente character varying(255) NOT NULL
);


ALTER TABLE public.discente_disciplina OWNER TO rinq;

--
-- Name: disciplina; Type: TABLE; Schema: public; Owner: rinq
--

CREATE TABLE public.disciplina (
    id bigint NOT NULL,
    carga_horaria integer NOT NULL,
    nome character varying(100) NOT NULL,
    id_curso bigint
);


ALTER TABLE public.disciplina OWNER TO rinq;

--
-- Name: disciplina_id_seq; Type: SEQUENCE; Schema: public; Owner: rinq
--

ALTER TABLE public.disciplina ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.disciplina_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: docente; Type: TABLE; Schema: public; Owner: rinq
--

CREATE TABLE public.docente (
    siape character varying(9) NOT NULL,
    login character varying(255) NOT NULL,
    id_curso bigint,
    id_disciplina bigint
);


ALTER TABLE public.docente OWNER TO rinq;

--
-- Name: falta; Type: TABLE; Schema: public; Owner: rinq
--

CREATE TABLE public.falta (
    id bigint NOT NULL,
    quantidade_faltas integer,
    id_aula bigint,
    matricula_discente character varying(11),
    id_disciplina bigint
);


ALTER TABLE public.falta OWNER TO rinq;

--
-- Name: falta_id_seq; Type: SEQUENCE; Schema: public; Owner: rinq
--

ALTER TABLE public.falta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.falta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hibernate_sequence; Type: SEQUENCE; Schema: public; Owner: rinq
--

CREATE SEQUENCE public.hibernate_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.hibernate_sequence OWNER TO rinq;

--
-- Name: password_reset_token; Type: TABLE; Schema: public; Owner: rinq
--

CREATE TABLE public.password_reset_token (
    id bigint NOT NULL,
    data_experiracao timestamp without time zone,
    token character varying(255),
    cpf_usuario character varying(255)
);


ALTER TABLE public.password_reset_token OWNER TO rinq;

--
-- Name: prova; Type: TABLE; Schema: public; Owner: rinq
--

CREATE TABLE public.prova (
    id bigint NOT NULL,
    media_final real,
    prova1 real,
    prova2 real,
    recuperacao1 real,
    recuperacao2 real,
    recuperacao_final real,
    matricula_discente character varying(11),
    id_disciplina bigint
);


ALTER TABLE public.prova OWNER TO rinq;

--
-- Name: prova_id_seq; Type: SEQUENCE; Schema: public; Owner: rinq
--

ALTER TABLE public.prova ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prova_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario; Type: TABLE; Schema: public; Owner: rinq
--

CREATE TABLE public.usuario (
    login character varying(255) NOT NULL,
    cpf character varying(14) NOT NULL,
    email character varying(100) NOT NULL,
    funcao character varying(14) NOT NULL,
    nome character varying(100) NOT NULL,
    senha character varying(60) NOT NULL
);


ALTER TABLE public.usuario OWNER TO rinq;

--
-- Data for Name: administrador; Type: TABLE DATA; Schema: public; Owner: rinq
--

COPY public.administrador (siape, login) FROM stdin;
\.


--
-- Data for Name: aula; Type: TABLE DATA; Schema: public; Owner: rinq
--

COPY public.aula (id, data, observacao, quantidade, id_disciplina, siape_docente) FROM stdin;
\.


--
-- Data for Name: curso; Type: TABLE DATA; Schema: public; Owner: rinq
--

COPY public.curso (id, nome, turno) FROM stdin;
1	An lise e Desenvolvimento de Sistemas	ManhÆ
2	Manuten‡Æo e Suporte em Inform tica	Tarde
3	Administra‡Æo	ManhÆ
4	Processos Gerenciais	Noite
\.


--
-- Data for Name: discente; Type: TABLE DATA; Schema: public; Owner: rinq
--

COPY public.discente (matricula, login, id_curso) FROM stdin;
\.


--
-- Data for Name: discente_disciplina; Type: TABLE DATA; Schema: public; Owner: rinq
--

COPY public.discente_disciplina (id_disciplina, cpf_discente) FROM stdin;
\.


--
-- Data for Name: disciplina; Type: TABLE DATA; Schema: public; Owner: rinq
--

COPY public.disciplina (id, carga_horaria, nome, id_curso) FROM stdin;
1	80	Empreendedorismo em Neg¢cios de TIC	1
2	40	Inicia‡Æo … Inform tica	1
3	80	Introdu‡Æo … Programa‡Æo	1
4	80	L¡ngua Inglesa Aplicada	1
5	80	Matem tica Aplicada	1
6	40	Etica e Responsabilidade Socioambiental	1
7	40	Arquitetura de Computadores	1
8	80	Banco de Dados I	1
9	80	Engenharia de Software	1
10	80	Linguagem de Programa‡Æo Orientada a Objetos	1
11	80	Estat¡stica Aplicada	1
12	80	Redes de Computadores	1
13	80	Algoritmos e Estruturas de Dados	1
14	80	Redes de Computadores	1
15	80	Algoritmos e Estruturas de Dados	1
16	80	An lise e Projeto de Sistemas	1
17	80	Banco de Dados II	1
18	80	Desenvolvimento de Sistemas Web I	1
19	80	Inteligˆncia Artificial	1
20	80	Desenvolvimento Sistemas Web II	1
21	80	Metodologia Cient¡fica Aplicada	1
22	80	Sistemas Distribu¡dos	1
23	80	Sistemas Operacionais	1
24	80	Aprendizagem de M quina	1
25	40	Projeto de Desenvolvimento de Sistemas Web	1
26	40	Introdu‡Æo Ao Trabalho de ConclusÆo de Curso	1
27	80	Teste de Software	1
28	80	Minera‡Æo de Dados	1
29	80	Gerenciamentos de Projetos	1
30	80	Programa‡Æo para Dispositivos M¢veis	1
31	60	Metodologia da Pesquisa	1
32	80	Seguran‡a da Informa‡Æo	1
33	80	T¢picos Especiais em Sistemas Operacionais	1
34	80	T¢picos Especiais em Sistemas Embarcados	1
35	80	T¢picos Especiais em Inteligˆncia Artificial	1
36	80	T¢picos Especiais em Eletr“nica	1
37	80	T¢picos Especiais em Engenharia de Software	1
38	80	T¢picos Especiais em Ciˆncia dos Dados	1
39	80	T¢picos Especiais em Banco de Dados	1
40	80	T¢picos Especiais em Redes de Computadores	1
41	80	Processos Ageis em Desenvolvimento de Software	1
42	80	Programa‡Æo Funcional	1
43	80	Desenvolvimento de Jogos	1
44	80	Libras	1
45	80	L¡ngua Portuguesa	1
46	80	Ergonomia de Software	1
47	80	Processamento Digital de Imagens	1
48	100	Inform tica B sica	2
49	80	Portuguˆs Instrumental	2
50	80	Inglˆs Instrumental	2
51	80	L¢gica de Programa‡Æo	2
52	60	Eletricidade B sica I	2
53	60	Direitos Humanos, Etica Profissional e Cidadania	2
54	80	Redes de Computadores	2
55	60	Sistemas Operacionais	2
56	40	Arquitetura de Computadores	2
57	80	Eletr“nica B sica II	2
58	30	Softwares Utilit rios	2
59	80	Montagem e Manuten‡Æo de Computadores I	2
60	80	Tecnologias da Informa‡Æo e Comunica‡Æo	2
61	60	Seguran‡a, Meio Ambiente e Sa£de	2
62	80	Administra‡Æo de Sistemas Operacionais	2
63	80	Montagem e Manuten‡Æo de Computadores II	2
64	80	Suporte a Usu rio	2
65	60	Empreendedorismo	2
66	100	Pr tica Profissional Supervisionada	2
67	80	Introdu‡Æo … Administra‡Æo	3
68	60	Estat¡stica B sica	3
69	80	Portuguˆs Instrumental	3
70	40	Etica Profissional	3
71	40	Inform tica B sica	3
72	40	GestÆo Ambiental	3
73	60	Matem tica Financeira	3
74	40	Legisla‡Æo Empresarial	3
75	40	GestÆo de Pessoas	3
76	60	GestÆo Financeira e Or‡ament ria	3
77	40	GestÆo de Qualidade, Produtos e Servi‡os	3
78	40	GestÆo de Materiais, Estoque e Compras	3
79	40	Tecnologia e Sistemas de Informa‡Æo Gerencial	3
80	40	No‡äes de Log¡stica	3
81	40	Reda‡Æo Oficial	3
82	60	GestÆo de Processo Produtivos	3
83	60	Seguran‡a e Sa£de no Trabalho	3
84	60	Empreendedorismo	3
85	40	Psicologia Organizacional e Rela‡äes Humanas	3
86	60	Legisla‡Æo Trabalhista, Previdenci ria e Tribut ria	3
87	40	Economia e Mercado	3
88	40	GestÆo de Marketing	3
89	60	Contabilidade B sica, gerencial e de Custos	3
90	80	Inglˆs Instrumental	3
91	60	GestÆo de Micro e Pequenas Empresas	3
92	80	Introdu‡Æo … Administra‡Æo	4
93	40	No‡äes de Direito Administrativo	4
94	60	Matem tica B sica	4
95	60	Introdu‡Æo … Economia	4
96	60	Sociologia Aplicada … Administra‡Æo	4
97	60	Introdu‡Æo … Contabilidade	4
98	80	Produ‡Æo Textual e Comunica‡Æo Empresarial	4
99	80	Estat¡stica B sica	4
100	40	Orat¢ria e Ret¢rica	4
101	40	Organiza‡Æo do Trabalho Cient¡fico	4
102	40	No‡äes de GestÆo P£blica	4
103	40	Etica	4
104	60	Reflexäes Cr¡ticas e Organiza‡äes	4
105	60	Psicologia Organizacional	4
106	60	Matem tica Financeira	4
107	60	Sistemas de Informa‡Æo Gerencial	4
108	60	GestÆo Ambiental e Sustentabilidade	4
109	60	No‡äes de Direito e Legisla‡Æo Empresarial	4
110	60	GestÆo de Custos	4
111	40	Processo Decis¢rio	4
112	80	GestÆo de Materiais e Log¡stica	4
113	60	Fundamentos da GestÆo da Qualidade	4
114	40	Est gio Curricular Supervisionado	4
115	40	Projeto Integrador I	4
116	60	Estrat‚gia Organizacional	4
117	60	GestÆo de Marketing	4
118	60	GestÆo Financeira e Or‡ament ria I	4
119	60	GestÆo de Pessoas	4
120	40	Introdu‡Æo ao Trabalho de ConclusÆo de Curso	4
121	40	Projeto Integrador II	4
122	60	GestÆo Financeira e Or‡ament ria II	4
123	60	Diagn¢stico e Consultoria Empresarial	4
124	40	Metodologia da Pesquisa	4
125	80	GestÆo da Produ‡Æo e Projetos	4
126	80	Empreendedorismo e GestÆo de Micro e Pequenas Empresas	4
127	40	Inform tica para Rotinas Administrativas	4
128	40	Economia Brasileira	4
129	40	Viabilidade Econ“mico-financeira	4
130	40	GestÆo no Terceiro Setor	4
131	60	No‡äes de Or‡amento P£blico	4
132	60	Direito de Trabalho	4
133	60	Departamento Pessoal	4
134	40	Macroeconomia	4
135	40	GestÆo de Organiza‡äes Tur¡sticas	4
136	40	E-business	4
137	40	Contabilidade Gerencial e An lise de Demonstra‡äes Financeiras	4
\.


--
-- Data for Name: docente; Type: TABLE DATA; Schema: public; Owner: rinq
--

COPY public.docente (siape, login, id_curso, id_disciplina) FROM stdin;
\.


--
-- Data for Name: falta; Type: TABLE DATA; Schema: public; Owner: rinq
--

COPY public.falta (id, quantidade_faltas, id_aula, matricula_discente, id_disciplina) FROM stdin;
\.


--
-- Data for Name: password_reset_token; Type: TABLE DATA; Schema: public; Owner: rinq
--

COPY public.password_reset_token (id, data_experiracao, token, cpf_usuario) FROM stdin;
\.


--
-- Data for Name: prova; Type: TABLE DATA; Schema: public; Owner: rinq
--

COPY public.prova (id, media_final, prova1, prova2, recuperacao1, recuperacao2, recuperacao_final, matricula_discente, id_disciplina) FROM stdin;
\.


--
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: rinq
--

COPY public.usuario (login, cpf, email, funcao, nome, senha) FROM stdin;
\.


--
-- Name: aula_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rinq
--

SELECT pg_catalog.setval('public.aula_id_seq', 1, false);


--
-- Name: curso_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rinq
--

SELECT pg_catalog.setval('public.curso_id_seq', 4, true);


--
-- Name: disciplina_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rinq
--

SELECT pg_catalog.setval('public.disciplina_id_seq', 137, true);


--
-- Name: falta_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rinq
--

SELECT pg_catalog.setval('public.falta_id_seq', 1, false);


--
-- Name: hibernate_sequence; Type: SEQUENCE SET; Schema: public; Owner: rinq
--

SELECT pg_catalog.setval('public.hibernate_sequence', 1, false);


--
-- Name: prova_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rinq
--

SELECT pg_catalog.setval('public.prova_id_seq', 1, false);


--
-- Name: administrador administrador_pkey; Type: CONSTRAINT; Schema: public; Owner: rinq
--

ALTER TABLE ONLY public.administrador
    ADD CONSTRAINT administrador_pkey PRIMARY KEY (login);


--
-- Name: aula aula_pkey; Type: CONSTRAINT; Schema: public; Owner: rinq
--

ALTER TABLE ONLY public.aula
    ADD CONSTRAINT aula_pkey PRIMARY KEY (id);


--
-- Name: curso curso_pkey; Type: CONSTRAINT; Schema: public; Owner: rinq
--

ALTER TABLE ONLY public.curso
    ADD CONSTRAINT curso_pkey PRIMARY KEY (id);


--
-- Name: discente discente_pkey; Type: CONSTRAINT; Schema: public; Owner: rinq
--

ALTER TABLE ONLY public.discente
    ADD CONSTRAINT discente_pkey PRIMARY KEY (login);


--
-- Name: disciplina disciplina_pkey; Type: CONSTRAINT; Schema: public; Owner: rinq
--

ALTER TABLE ONLY public.disciplina
    ADD CONSTRAINT disciplina_pkey PRIMARY KEY (id);


--
-- Name: docente docente_pkey; Type: CONSTRAINT; Schema: public; Owner: rinq
--

ALTER TABLE ONLY public.docente
    ADD CONSTRAINT docente_pkey PRIMARY KEY (login);


--
-- Name: falta falta_pkey; Type: CONSTRAINT; Schema: public; Owner: rinq
--

ALTER TABLE ONLY public.falta
    ADD CONSTRAINT falta_pkey PRIMARY KEY (id);


--
-- Name: password_reset_token password_reset_token_pkey; Type: CONSTRAINT; Schema: public; Owner: rinq
--

ALTER TABLE ONLY public.password_reset_token
    ADD CONSTRAINT password_reset_token_pkey PRIMARY KEY (id);


--
-- Name: prova prova_pkey; Type: CONSTRAINT; Schema: public; Owner: rinq
--

ALTER TABLE ONLY public.prova
    ADD CONSTRAINT prova_pkey PRIMARY KEY (id);


--
-- Name: discente uk_6p01sdr7hxjle5wpbev5egwvw; Type: CONSTRAINT; Schema: public; Owner: rinq
--

ALTER TABLE ONLY public.discente
    ADD CONSTRAINT uk_6p01sdr7hxjle5wpbev5egwvw UNIQUE (matricula);


--
-- Name: docente uk_dd75d7dsh8yve7os2gaq1227u; Type: CONSTRAINT; Schema: public; Owner: rinq
--

ALTER TABLE ONLY public.docente
    ADD CONSTRAINT uk_dd75d7dsh8yve7os2gaq1227u UNIQUE (siape);


--
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: rinq
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (login);


--
-- Name: docente fk130gvra2oqyaugr9n73nxp3y; Type: FK CONSTRAINT; Schema: public; Owner: rinq
--

ALTER TABLE ONLY public.docente
    ADD CONSTRAINT fk130gvra2oqyaugr9n73nxp3y FOREIGN KEY (id_disciplina) REFERENCES public.disciplina(id);


--
-- Name: password_reset_token fk2hflui8rva3heydm0dvppe4hy; Type: FK CONSTRAINT; Schema: public; Owner: rinq
--

ALTER TABLE ONLY public.password_reset_token
    ADD CONSTRAINT fk2hflui8rva3heydm0dvppe4hy FOREIGN KEY (cpf_usuario) REFERENCES public.usuario(login);


--
-- Name: aula fk5dcivvifocdsosppxnyniyxop; Type: FK CONSTRAINT; Schema: public; Owner: rinq
--

ALTER TABLE ONLY public.aula
    ADD CONSTRAINT fk5dcivvifocdsosppxnyniyxop FOREIGN KEY (siape_docente) REFERENCES public.docente(siape);


--
-- Name: administrador fk7gxh6rkycigify40f3r64n2mo; Type: FK CONSTRAINT; Schema: public; Owner: rinq
--

ALTER TABLE ONLY public.administrador
    ADD CONSTRAINT fk7gxh6rkycigify40f3r64n2mo FOREIGN KEY (login) REFERENCES public.usuario(login);


--
-- Name: falta fk99v9wg87jym71xhily7km548y; Type: FK CONSTRAINT; Schema: public; Owner: rinq
--

ALTER TABLE ONLY public.falta
    ADD CONSTRAINT fk99v9wg87jym71xhily7km548y FOREIGN KEY (id_aula) REFERENCES public.aula(id);


--
-- Name: docente fkdv543c6n1d3kptsuxqwjl1hyr; Type: FK CONSTRAINT; Schema: public; Owner: rinq
--

ALTER TABLE ONLY public.docente
    ADD CONSTRAINT fkdv543c6n1d3kptsuxqwjl1hyr FOREIGN KEY (id_curso) REFERENCES public.curso(id);


--
-- Name: falta fkghvsl6r930fei2olquqr04aif; Type: FK CONSTRAINT; Schema: public; Owner: rinq
--

ALTER TABLE ONLY public.falta
    ADD CONSTRAINT fkghvsl6r930fei2olquqr04aif FOREIGN KEY (id_disciplina) REFERENCES public.disciplina(id);


--
-- Name: prova fkixry34vo453p7sx9jqa2l0qhk; Type: FK CONSTRAINT; Schema: public; Owner: rinq
--

ALTER TABLE ONLY public.prova
    ADD CONSTRAINT fkixry34vo453p7sx9jqa2l0qhk FOREIGN KEY (id_disciplina) REFERENCES public.disciplina(id);


--
-- Name: docente fkldoouqxd68eu7jshgktsib3a4; Type: FK CONSTRAINT; Schema: public; Owner: rinq
--

ALTER TABLE ONLY public.docente
    ADD CONSTRAINT fkldoouqxd68eu7jshgktsib3a4 FOREIGN KEY (login) REFERENCES public.usuario(login);


--
-- Name: discente fklo410sq5gus4yl878masi903c; Type: FK CONSTRAINT; Schema: public; Owner: rinq
--

ALTER TABLE ONLY public.discente
    ADD CONSTRAINT fklo410sq5gus4yl878masi903c FOREIGN KEY (id_curso) REFERENCES public.curso(id);


--
-- Name: falta fkloy3igy0g2b3shcs347wfusoa; Type: FK CONSTRAINT; Schema: public; Owner: rinq
--

ALTER TABLE ONLY public.falta
    ADD CONSTRAINT fkloy3igy0g2b3shcs347wfusoa FOREIGN KEY (matricula_discente) REFERENCES public.discente(matricula);


--
-- Name: disciplina fkncelm81kvdx8m08q5rbpn2jru; Type: FK CONSTRAINT; Schema: public; Owner: rinq
--

ALTER TABLE ONLY public.disciplina
    ADD CONSTRAINT fkncelm81kvdx8m08q5rbpn2jru FOREIGN KEY (id_curso) REFERENCES public.curso(id);


--
-- Name: discente_disciplina fknlivoqch33xa69gheal1s6jj5; Type: FK CONSTRAINT; Schema: public; Owner: rinq
--

ALTER TABLE ONLY public.discente_disciplina
    ADD CONSTRAINT fknlivoqch33xa69gheal1s6jj5 FOREIGN KEY (id_disciplina) REFERENCES public.disciplina(id);


--
-- Name: aula fknxilct2rqynmw6c2sh2w61w2s; Type: FK CONSTRAINT; Schema: public; Owner: rinq
--

ALTER TABLE ONLY public.aula
    ADD CONSTRAINT fknxilct2rqynmw6c2sh2w61w2s FOREIGN KEY (id_disciplina) REFERENCES public.disciplina(id);


--
-- Name: discente_disciplina fkqwbdkl3hnl9x5nvxpusqhnheh; Type: FK CONSTRAINT; Schema: public; Owner: rinq
--

ALTER TABLE ONLY public.discente_disciplina
    ADD CONSTRAINT fkqwbdkl3hnl9x5nvxpusqhnheh FOREIGN KEY (cpf_discente) REFERENCES public.discente(login);


--
-- Name: discente fks8775tu5rlthx28mfd9sqpa7m; Type: FK CONSTRAINT; Schema: public; Owner: rinq
--

ALTER TABLE ONLY public.discente
    ADD CONSTRAINT fks8775tu5rlthx28mfd9sqpa7m FOREIGN KEY (login) REFERENCES public.usuario(login);


--
-- Name: prova fks9rxyvxvh7y0stynd7fsn0xld; Type: FK CONSTRAINT; Schema: public; Owner: rinq
--

ALTER TABLE ONLY public.prova
    ADD CONSTRAINT fks9rxyvxvh7y0stynd7fsn0xld FOREIGN KEY (matricula_discente) REFERENCES public.discente(matricula);


--
-- PostgreSQL database dump complete
--

